In [ ]:
%pip install pandas numpy scikit-learn kaggle kagglehub

In [1]:
import kagglehub

# Download latest version
#https://www.kaggle.com/datasets/anupammajhi/uber-request-data
path = kagglehub.dataset_download("anupammajhi/uber-request-data")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/anupammajhi/uber-request-data?dataset_version_number=1...

100%|██████████| 66.1k/66.1k [00:00<00:00, 7.28MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/anupammajhi/uber-request-data/versions/1

In [3]:
!ls /root/.cache/kagglehub/datasets/anupammajhi/uber-request-data/versions/1

'Uber Request Data.csv'

In [4]:
import pandas as pd

pd.read_csv("/root/.cache/kagglehub/datasets/anupammajhi/uber-request-data/versions/1/Uber Request Data.csv")

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
0,619,Airport,1.0,Trip Completed,11/7/2016 11:51,11/7/2016 13:00
1,867,Airport,1.0,Trip Completed,11/7/2016 17:57,11/7/2016 18:47
2,1807,City,1.0,Trip Completed,12/7/2016 9:17,12/7/2016 9:58
3,2532,Airport,1.0,Trip Completed,12/7/2016 21:08,12/7/2016 22:03
4,3112,City,1.0,Trip Completed,13-07-2016 08:33:16,13-07-2016 09:25:47
...,...,...,...,...,...,...
6740,6745,City,NaN,No Cars Available,15-07-2016 23:49:03,NaN
6741,6752,Airport,NaN,No Cars Available,15-07-2016 23:50:05,NaN
6742,6751,City,NaN,No Cars Available,15-07-2016 23:52:06,NaN
6743,6754,City,NaN,No Cars Available,15-07-2016 23:54:39,NaN
6744,6753,Airport,NaN,No Cars Available,15-07-2016 23:55:03,NaN

In [ ]:
df = pd.read_csv("/root/.cache/kagglehub/datasets/anupammajhi/uber-request-data/versions/1/Uber Request Data.csv")
df.head(n=10)

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
0,619,Airport,1.0,Trip Completed,11/7/2016 11:51,11/7/2016 13:00
1,867,Airport,1.0,Trip Completed,11/7/2016 17:57,11/7/2016 18:47
2,1807,City,1.0,Trip Completed,12/7/2016 9:17,12/7/2016 9:58
3,2532,Airport,1.0,Trip Completed,12/7/2016 21:08,12/7/2016 22:03
4,3112,City,1.0,Trip Completed,13-07-2016 08:33:16,13-07-2016 09:25:47
5,3879,Airport,1.0,Trip Completed,13-07-2016 21:57:28,13-07-2016 22:28:59
6,4270,Airport,1.0,Trip Completed,14-07-2016 06:15:32,14-07-2016 07:13:15
7,5510,Airport,1.0,Trip Completed,15-07-2016 05:11:52,15-07-2016 06:07:52
8,6248,City,1.0,Trip Completed,15-07-2016 17:57:27,15-07-2016 18:50:51
9,267,City,2.0,Trip Completed,11/7/2016 6:46,11/7/2016 7:25

In [ ]:
df.index

RangeIndex(start=0, stop=6745, step=1)

In [ ]:
df.shape

(6745, 6)

In [ ]:
df.dtypes

Request id             int64
Pickup point          object
Driver id            float64
Status                object
Request timestamp     object
Drop timestamp        object
dtype: object

In [ ]:
df.columns

Index(['Request id', 'Pickup point', 'Driver id', 'Status',
       'Request timestamp', 'Drop timestamp'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6745 entries, 0 to 6744
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Request id         6745 non-null   int64
 1   Pickup point       6745 non-null   object
 2   Driver id          4095 non-null   float64
 3   Status             6745 non-null   object
 4   Request timestamp  6745 non-null   object
 5   Drop timestamp     2831 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 316.3+ KB

In [ ]:
df.describe()

        Request id    Driver id
count  6745.000000  4095.000000
mean   3384.644922   149.501343
std    1955.099667    86.051994
min       1.000000     1.000000
25%    1691.000000    75.000000
50%    3387.000000   149.000000
75%    5080.000000   224.000000
max    6766.000000   300.000000

In [ ]:
df.isnull().sum()

Request id              0
Pickup point            0
Driver id            2650
Status                  0
Request timestamp       0
Drop timestamp       3914
dtype: int64

In [ ]:
df.sort_index(axis=1,
ascending=False)

,Status,Request timestamp,Request id,Pickup point,Drop timestamp,Driver id
0,Trip Completed,11/7/2016 11:51,619,Airport,11/7/2016 13:00,1.0
1,Trip Completed,11/7/2016 17:57,867,Airport,11/7/2016 18:47,1.0
2,Trip Completed,12/7/2016 9:17,1807,City,12/7/2016 9:58,1.0
3,Trip Completed,12/7/2016 21:08,2532,Airport,12/7/2016 22:03,1.0
4,Trip Completed,13-07-2016 08:33:16,3112,City,13-07-2016 09:25:47,1.0
...,...,...,...,...,...,...
6740,No Cars Available,15-07-2016 23:49:03,6745,City,NaN,NaN
6741,No Cars Available,15-07-2016 23:50:05,6752,Airport,NaN,NaN
6742,No Cars Available,15-07-2016 23:52:06,6751,City,NaN,NaN
6743,No Cars Available,15-07-2016 23:54:39,6754,City,NaN,NaN
6744,No Cars Available,15-07-2016 23:55:03,6753,Airport,NaN,NaN

In [ ]:
df.sort_values(by="Request id")

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
2700,1,Airport,285.0,Trip Completed,11/7/2016 0:20,11/7/2016 0:51
4098,2,Airport,NaN,No Cars Available,11/7/2016 0:23,NaN
776,3,Airport,80.0,Trip Completed,11/7/2016 0:24,11/7/2016 1:31
4101,4,City,NaN,No Cars Available,11/7/2016 0:37,NaN
2506,5,Airport,264.0,Trip Completed,11/7/2016 0:36,11/7/2016 1:35
...,...,...,...,...,...,...
2534,6762,Airport,267.0,Trip Completed,15-07-2016 00:07:29,15-07-2016 00:52:50
2137,6763,City,224.0,Trip Completed,15-07-2016 00:04:44,15-07-2016 01:06:42
2324,6764,City,243.0,Trip Completed,15-07-2016 00:06:12,15-07-2016 01:17:53
6165,6765,Airport,NaN,No Cars Available,15-07-2016 00:09:09,NaN
1042,6766,City,108.0,Trip Completed,15-07-2016 00:06:56,15-07-2016 01:10:34

In [ ]:
df.iloc[5]

Request id                          3879
Pickup point                     Airport
Driver id                            1.0
Status                    Trip Completed
Request timestamp    13-07-2016 21:57:28
Drop timestamp       13-07-2016 22:28:59
Name: 5, dtype: object

In [ ]:
df[0:4]

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
0,619,Airport,1.0,Trip Completed,11/7/2016 11:51,11/7/2016 13:00
1,867,Airport,1.0,Trip Completed,11/7/2016 17:57,11/7/2016 18:47
2,1807,City,1.0,Trip Completed,12/7/2016 9:17,12/7/2016 9:58
3,2532,Airport,1.0,Trip Completed,12/7/2016 21:08,12/7/2016 22:03

In [ ]:
df.loc[:, ["Request id","Status"]]

      Request id             Status
0            619     Trip Completed
1            867     Trip Completed
2           1807     Trip Completed
3           2532     Trip Completed
4           3112     Trip Completed
...          ...                ...
6740        6745  No Cars Available
6741        6752  No Cars Available
6742        6751  No Cars Available
6743        6754  No Cars Available
6744        6753  No Cars Available

[6745 rows x 2 columns]

In [ ]:
# Return the last n rows.
display(df.tail(n=5))

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
6740,6745,City,NaN,No Cars Available,15-07-2016 23:49:03,NaN
6741,6752,Airport,NaN,No Cars Available,15-07-2016 23:50:05,NaN
6742,6751,City,NaN,No Cars Available,15-07-2016 23:52:06,NaN
6743,6754,City,NaN,No Cars Available,15-07-2016 23:54:39,NaN
6744,6753,Airport,NaN,No Cars Available,15-07-2016 23:55:03,NaN

In [ ]:
# Return the columns values in the Dataset in array format
display(df.columns.values)

array(['Request id', 'Pickup point', 'Driver id', 'Status',
       'Request timestamp', 'Drop timestamp'], dtype=object)

In [ ]:
# Displaying the first 3 columns
display(df.iloc[:, :3])

      Request id Pickup point  Driver id
0            619      Airport        1.0
1            867      Airport        1.0
2           1807         City        1.0
3           2532      Airport        1.0
4           3112         City        1.0
...          ...          ...        ...
6740        6745         City        NaN
6741        6752      Airport        NaN
6742        6751         City        NaN
6743        6754         City        NaN
6744        6753      Airport        NaN

[6745 rows x 3 columns]

In [ ]:
# Displaying the first 5 rows and first 3 columns
display(df.iloc[:5, :3])

   Request id Pickup point  Driver id
0         619      Airport        1.0
1         867      Airport        1.0
2        1807         City        1.0
3        2532      Airport        1.0
4        3112         City        1.0

## Data Formatting

### 1. Checking Data Types (`df.dtypes`)

In [ ]:
# Display the current data types of the DataFrame
print("Current Data Types:")
display(df.dtypes)

Current Data Types:

Request id             int64
Pickup point          object
Driver id            float64
Status                object
Request timestamp     object
Drop timestamp        object
dtype: object

### 2. Converting Data Types (`df.astype()` and `pd.to_datetime`)

In [ ]:
# Convert 'Request timestamp' and 'Drop timestamp' to datetime objects
# Using errors='coerce' will turn unparseable dates into NaT (Not a Time)
df['Request timestamp'] = pd.to_datetime(df['Request timestamp'], errors='coerce')
df['Drop timestamp'] = pd.to_datetime(df['Drop timestamp'], errors='coerce')

# Convert 'Driver id' to integer type, handling NaN values by allowing them (float still works for NaN)
df['Driver id'] = df['Driver id'].astype('Int64')

print("\nData Types after conversion:")
display(df.dtypes)
display(df.head())

Data Types after conversion:

Request id                    int64
Pickup point                 object
Driver id                     Int64
Status                       object
Request timestamp    datetime64[ns]
Drop timestamp       datetime64[ns]
dtype: object

,Request id,Pickup point,Driver id,Status,Request timestamp,Drop timestamp
0,619,Airport,1,Trip Completed,2016-11-07 11:51:00,2016-11-07 13:00:00
1,867,Airport,1,Trip Completed,2016-11-07 17:57:00,2016-11-07 18:47:00
2,1807,City,1,Trip Completed,2016-12-07 09:17:00,2016-12-07 09:58:00
3,2532,Airport,1,Trip Completed,2016-12-07 21:08:00,2016-12-07 22:03:00
4,3112,City,1,Trip Completed,NaT,NaT

## Encoding Categorical Features

### 1. Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to the 'Pickup point' column
df['Pickup point_encoded'] = le.fit_transform(df['Pickup point'])

print("\nDataFrame with Label Encoded 'Pickup point' column:")
display(df[['Pickup point', 'Pickup point_encoded']].head())

DataFrame with Label Encoded 'Pickup point' column:

  Pickup point  Pickup point_encoded
0      Airport                     0
1      Airport                     0
2         City                     1
3      Airport                     0
4         City                     1

### 2. One-Hot Encoding

In [ ]:
# Apply One-Hot Encoding to the 'Status' column

df_one_hot = pd.get_dummies(df, columns=['Status'], prefix='Status')

print("\nDataFrame with One-Hot Encoded 'Status' column (first 5 rows and relevant columns):")
display(df_one_hot[['Status_Cancelled', 'Status_No Cars Available', 'Status_Trip Completed']].head())

DataFrame with One-Hot Encoded 'Status' column (first 5 rows and relevant columns):

   Status_Cancelled  Status_No Cars Available  Status_Trip Completed
0             False                     False                   True
1             False                     False                   True
2             False                     False                   True
3             False                     False                   True
4             False                     False                   True

##Pre-Processing Steps

1. Normalization

In [ ]:
from sklearn import preprocessing
print("Raw Data:")
print(df.head())

# Normalization only works on numbers.
x = df.select_dtypes(include=['number'])

# Create a minimum and maximum processor object
min_max_scaler = preprocessing.MinMaxScaler()

# Create an object to transform the data to fit minmax processor
# This calculates the min/max and scales the data in one go
x_scaled = min_max_scaler.fit_transform(x)

# Run the normalizer on the dataframe
# We turn the resulting array back into a readable Pandas DataFrame
df_normalized = pd.DataFrame(x_scaled, columns=x.columns)

print("\nNormalized Data (Values scaled between 0 and 1):")
print(df_normalized.head())

Raw Data:
   Request id Pickup point  Driver id          Status    Request timestamp  \
0         619      Airport        1.0  Trip Completed      11/7/2016 11:51
1         867      Airport        1.0  Trip Completed      11/7/2016 17:57
2        1807         City        1.0  Trip Completed       12/7/2016 9:17
3        2532      Airport        1.0  Trip Completed      12/7/2016 21:08
4        3112         City        1.0  Trip Completed  13-07-2016 08:33:16

        Drop timestamp
0      11/7/2016 13:00
1      11/7/2016 18:47
2       12/7/2016 9:58
3      12/7/2016 22:03
4  13-07-2016 09:25:47

Normalized Data (Values scaled between 0 and 1):
   Request id  Driver id
0    0.091353        0.0
1    0.128012        0.0
2    0.266962        0.0
3    0.374132        0.0
4    0.459867        0.0